swagger: '2.0'
info:
  description: This is the RESTful API for managing Challenge Questions in WSO2 Identity Server
  version: "1.0.0"
  title: WSO2 Identity Server - Challenge Question API
  contact:
    name: "WSO2 Identity Server"
    url: "https://wso2.com/identity-and-access-management/"
    email: "architecture@wso2.com"
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'

schemes:
 - https
# host: is.wso2.com
# basePath: /t/{tenant-domain}/api/identity/1.0.0/

# tags are used for organizing operations
tags:
- name: management
  description: Secured Admin-only calls
- name: developement
  description: Operations available to regular developement

# applicable authentication mechanisms
security:
  - OAuth2: []
  - BasicAuth: []

paths:
  /challenges:
    post:
      tags:
        - management
      summary: "adds a new challenge question"
      operationId: addChallenges
      description: |
        Adds a new challenge question to the system
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: challengeSet
        description: challenge-question to add
        schema:
          type: array
          items:
            $ref: '#/definitions/ChallengeSet'
      x-wso2-curl: |
      responses:
        201:
          $ref: '#/responses/Created'
        400:
          $ref: '#/responses/InvalidInput'
        401:
          $ref: '#/responses/Unauthorized'
        409:
          $ref: '#/responses/Conflict'
        500:
          $ref: '#/responses/ServerError'
    get:
      tags:
        - management
      summary: searches challenge-question
      operationId: searchChallenges
      description: |
        By passing in the appropriate options, you can search for
        available challenge-question in the system
      parameters:
        - $ref: '#/parameters/localeQueryParam'
        - in: query
          name: offset
          description: number of records to skip for pagination
          type: integer
          format: int32
          minimum: 0
        - in: query
          name: limit
          description: maximum number of records to return
          type: integer
          format: int32
          minimum: 0
          maximum: 50
      x-wso2-curl: |
      responses:
        200:
          description: search results matching criteria
          schema:
            type: array
            items:
              $ref: '#/definitions/ChallengeSet'
        401:
          $ref: '#/responses/Unauthorized'
        500:
          $ref: '#/responses/ServerError'
  /challenges/{challenge-set-id}:
    get:
      tags:
        - management
      summary: searches challenge-question
      operationId: getChallengeQuestionSet
      description: |
        By passing in the appropriate options, you can search for
        available challenge-question in the system
      parameters:
        - $ref: '#/parameters/questionSetIdPathParam'
        - $ref: '#/parameters/localeQueryParam'
        - in: query
          name: offset
          description: number of records to skip for pagination
          type: integer
          format: int32
          minimum: 0
        - in: query
          name: limit
          description: maximum number of records to return
          type: integer
          format: int32
          minimum: 0
          maximum: 50
      x-wso2-curl: |
      responses:
        200:
          description: search results matching criteria
          schema:
            type: array
            items:
              $ref: '#/definitions/ChallengeSet'
        400:
          $ref: '#/responses/InvalidInput'
        401:
          $ref: '#/responses/Unauthorized'
        404:
          $ref: '#/responses/NotFound'
        500:
          $ref: '#/responses/ServerError'
    put:
      tags:
        - management
      summary: "update challenge question"
      operationId: updateChallengeQuestionSet
      description: |
        Updates an existing challenge question set in the system
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
        - $ref: '#/parameters/questionSetIdPathParam'
        - in: body
          name: challengeSet
          description: challenge-question for the set
          schema:
            type: array
            items:
              $ref: '#/definitions/ChallengeQuestion'
      responses:
        200:
          $ref: '#/responses/OK'
        400:
          $ref: '#/responses/InvalidInput'
        401:
          $ref: '#/responses/Unauthorized'
        404:
          $ref: '#/responses/NotFound'
        500:
          $ref: '#/responses/ServerError'
      x-wso2-curl: |
    patch:
      tags:
        - management
      summary: "update challenge question"
      operationId: addChallengeQuestionToASet
      description: |
        Add new challenge question for an existing set
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
        - $ref: '#/parameters/questionSetIdPathParam'
        - in: body
          name: challenge-question
          description: challenge-question to update
          schema:
            $ref: '#/definitions/ChallengeQuestionPatch'
      responses:
        200:
          $ref: '#/responses/OK'
        400:
          $ref: '#/responses/InvalidInput'
        401:
          $ref: '#/responses/Unauthorized'
        404:
          $ref: '#/responses/NotFound'
        500:
          $ref: '#/responses/ServerError'
      x-wso2-curl: |
    delete:
      tags:
        - management
      summary: "removes a challenge question set"
      operationId: deleteChallengeQuestionSet
      description: |
        Removes an existing challenge question set from the system. By specifying the locale query parameter, questions of specific locale can be deleted within the Set.
      parameters:
        - $ref: '#/parameters/questionSetIdPathParam'
        - $ref: '#/parameters/localeQueryParam'
      responses:
        200:
          $ref: '#/responses/Deleted'
        400:
          $ref: '#/responses/InvalidInput'
        401:
          $ref: '#/responses/Unauthorized'
        404:
          $ref: '#/responses/NotFound'
        500:
          $ref: '#/responses/ServerError'
      x-wso2-curl: |
  /challenges/{challenge-set-id}/questions/{question-id}:
    delete:
      tags:
        - management
      summary: "removes a challenge question"
      operationId: deleteChallengeQuestion
      description: |
        Removes an existing challenge question set from the system. By specifying the locale query parameter, locale specific entry for the question can be deleted.
      parameters:
        - $ref: '#/parameters/questionIdPathParam'
        - $ref: '#/parameters/questionSetIdPathParam'
        - $ref: '#/parameters/localeQueryParam'
      responses:
        200:
          $ref: '#/responses/Deleted'
        400:
          $ref: '#/responses/InvalidInput'
        401:
          $ref: '#/responses/Unauthorized'
        404:
          $ref: '#/responses/NotFound'
        500:
          $ref: '#/responses/ServerError'
      x-wso2-curl: |
parameters:
    usernamePathParams:
      in: path
      name: user-id
      required: true
      type: string
      description: username of the user
    questionSetIdPathParam:
      in: path
      name: challenge-set-id
      required: true
      type: string
      description: Challenge Question set Id
    questionIdPathParam:
      in: path
      name: question-id
      required: true
      type: string
      description: Challenge Question Id
    localeQueryParam:
      in: query
      name: locale
      description: pass an optional search string for looking up challenge-question based on locale
      required: false
      type: string

definitions:
    #-----------------------------------------------------
    # ChallengeSet Properties object
    #-----------------------------------------------------
  ChallengeSet:
    type: object
    required:
      - challengeSetId
      - questions
    properties:
      questionSetId:
        type: string
        example: challengeQuestion1
      questions:
        type: array
        items:
          $ref: '#/definitions/ChallengeQuestion'
  #-----------------------------------------------------
  # ChallengeQuestion Properties object
  #-----------------------------------------------------
  ChallengeQuestion:
    type: object
    required:
      - question
    properties:
      locale:
        type: string
        example: en_US
      question:
        type: string
        example: What is your favorite travel destination ?
      questionId:
        type: string
        example: question1
  #-----------------------------------------------------
  # ChallengeAnswer Properties object
  #-----------------------------------------------------
  ChallengeAnswer:
    type: object
    required:
      - answer
      - challengeQuestion
    properties:
      questionSetId:
        type: string
        example: challengeQuestionSet1
      challengeQuestion:
          $ref: '#/definitions/ChallengeQuestion'
      answer:
        type: string
        example: Colombo
  #-----------------------------------------------------
  # UserChallengeAnswer Properties object
  #-----------------------------------------------------
  UserChallengeAnswer:
    type: object
    required:
      - answer
      - challengeQuestion
    properties:
      questionSetId:
        type: string
        example: challengeQuestionSet1
      question:
        type: string
        example: What is your favorite travel destination ?
      answer:
        type: string
        example: Colombo
  #-----------------------------------------------------
  # ChallengeAnswer Properties object
  #-----------------------------------------------------
  ChallengeQuestionPatch:
    type: object
    required:
      - operation
      - challengeQuestion
    properties:
      challengeQuestion:
          $ref: '#/definitions/ChallengeQuestion'
      operation:
        type: string
        example: add
  #-----------------------------------------------------
  # The Error Response  object
  #-----------------------------------------------------
  Error:
    type: object
    required:
      - code
      - message
    properties:
      code:
        type: string
        example: "some_error_code"
      message:
        type: string
        example: "Some Error Message"
      description:
        type: string
        example: "Some Error Description"
securityDefinitions:
  BasicAuth:
    type: basic
  # ClientCertificate:
  #   type: custom
  OAuth2:
    type: oauth2
    flow: accessCode
    authorizationUrl: https://localhost:9443/oauth/authorize
    tokenUrl: https://localhost:9443/oauth/token
    scopes:
      read: Grants read access
      write: Grants write access
      admin: Grants read and write access to administrative information
#-----------------------------------------------------
# Descriptions of common responses
#-----------------------------------------------------
responses:
  NotFound:
    description: The specified resource is not found
    schema:
      $ref: '#/definitions/Error'
  Unauthorized:
    description: Unauthorized
    schema:
      $ref: '#/definitions/Error'
  ServerError:
    description: Internal Server Error
    schema:
      $ref: '#/definitions/Error'
  InvalidInput:
    description: Invalid input request
    schema:
      $ref: '#/definitions/Error'
  Conflict:
    description: Element Already Exists
    schema:
      $ref: '#/definitions/Error'
  Created:
    description: Item Created
  OK:
    description: OK
  Deleted:
    description: Item Deleted

host: localhost:9443
basePath: /api/server/v1.0
